---
# tasks file for my_kde_role
- name: System details
  ansible.builtin.debug:
    msg: "{{ item }}"
  with_items: 
  - "ansible_os_family: {{ ansible_os_family }}"
  - "ansible_distribution: {{ ansible_distribution }}"
  - "ansible_distribution_release: {{ ansible_distribution_release }}"
  - "ansible_distribution_version: {{ ansible_distribution_version }}"
  - "ansible_distribution_major_version: {{ ansible_distribution_major_version }}"

- name: Override package name for Ubuntu.
  ansible.builtin.set_fact:
    kde_spectacle: kde-spectacle
  when: ansible_os_family == 'Debian'

- name: Install Kde Packages
  become: true
  ansible.builtin.package:
    state: present
    name:
    - kate
    - "{{ kde_spectacle }}"
    - ark
    - konsole
    - dolphin
    - okular
    - gwenview
    - yakuake
    - korganizer
    - kaddressbook
    - kdepim-addons
    - kio-gdrive
    - dolphin-plugins
    - plasma-systemmonitor
    - kdeplasma-addons
    - kcalc
    - plasma-workspace-wallpapers
    - kvantum
#    - latte-dock # it's not maintained anymore
