---
# tasks file for my_kde_role
- name: System details
  ansible.builtin.debug:
    msg: "{{ item }}"
  with_items: 
  - "ansible_os_family: {{ ansible_os_family }}"
  - "ansible_distribution: {{ ansible_distribution }}"
  - "ansible_distribution_release: {{ ansible_distribution_release }}"
  - "ansible_distribution_version: {{ ansible_distribution_version }}"
  - "ansible_distribution_major_version: {{ ansible_distribution_major_version }}"

- name: Override spectacle package name for Ubuntu.
  ansible.builtin.set_fact:
    kde_spectacle: kde-spectacle
  when: ansible_os_family == 'Debian'

- name: Override kvantum package name for Ubuntu.
  ansible.builtin.set_fact:
    kvantum: qt5-style-kvantum
  when: ansible_os_family == 'Debian'

- name: Install Kde Packages
  become: true
  ansible.builtin.package:
    state: present
    name:
    - kate
    - "{{ kde_spectacle }}"
    - ark
    - konsole
    - dolphin
    - okular
    - gwenview
    - yakuake
    - korganizer
    - kaddressbook
    - kdepim-addons
    - kio-gdrive
    - dolphin-plugins
    - plasma-systemmonitor
    - kcalc
    - plasma-workspace-wallpapers
    - "{{ kvantum }}"
#    - latte-dock # it's not maintained anymore

# In Ubuntu doesn't seem to be there
# maybe it's not needed
- name: Install Kde Addons
  become: true
  ansible.builtin.package:
    state: present
    name:
    - kdeplasma-addons
  when: ansible_os_family != 'Debian'

- name: Meta for Expose (Toggle Present Windows)
  community.general.ini_file:
    path: ~/.config/kwinrc
    section: ModifierOnlyShortcuts
    option: Meta
    value: org.kde.kglobalaccel,/component/kwin,org.kde.kglobalaccel.Component,invokeShortcut,Expose
    no_extra_spaces: yes
    mode: 0600

- name: Desktop effects
  community.general.ini_file:
    path: ~/.config/kwinrc
    section: '{{ item.section }}'
    option: '{{ item.option }}'
    value: '{{ item.value }}'
    no_extra_spaces: yes
    mode: 0600
  loop:
  - section: Plugins
    option: kwin4_effect_squashEnabled
    value: 'false'
  - section: Effect-MagicLamp
    option: AnimationDuration
    value: '400'
  - section: Plugins
    option: magiclampEnabled
    value: 'true'

- name: Switcher
  community.general.ini_file:
    path: ~/.config/kwinrc
    section: '{{ item.section }}'
    option: '{{ item.option }}'
    value: '{{ item.value }}'
    no_extra_spaces: yes
    mode: 0600
  loop:
  - section: TabBox
    option: HighlightWindows
    value: 'false'
  - section: TabBox
    option: LayoutName
    value: compact

- name: Ctrl+Alt+T for Konsole
  community.general.ini_file:
    path: ~/.config/kglobalshortcutsrc
    section: org.kde.konsole.desktop
    option: '{{ item.option }}'
    value: '{{ item.value }}'
    no_extra_spaces: yes
    mode: 0600
  loop:
  - option: _k_friendly_name
    value: Konsole
  - option: _launch
    value: Ctrl+Alt+T,Ctrl+Alt+T,Konsole

- name: Meta+X for ExposeAll (Toggle Present Windows (All desktops))
  community.general.ini_file:
    path: ~/.config/kglobalshortcutsrc
    section: kwin
    option: ExposeAll
    value: Meta+Z\tLaunch (C)\tCtrl+F10,Ctrl+F10\tLaunch (C),Toggle Present Windows (All desktops)
    no_extra_spaces: yes
    mode: 0600

- name: Meta+Z for ExposeClass (Toggle Present Windows (Window class))
  community.general.ini_file:
    path: ~/.config/kglobalshortcutsrc
    section: kwin
    option: ExposeClass
    value: Ctrl+F7\tMeta+X,Ctrl+F7,Toggle Present Windows (Window class)
    no_extra_spaces: yes
    mode: 0600

- name: Alt+\ (Walk Through Windows of Current Application)
  community.general.ini_file:
    path: ~/.config/kglobalshortcutsrc
    section: kwin
    option: Walk Through Windows of Current Application
    value: Alt+\\\\,Alt+`,Walk Through Windows of Current Application
    no_extra_spaces: yes
    mode: 0600

# In Fedora it's not installed by default
- name: Ensure xdg-mime is available
  become: true
  ansible.builtin.package:
    state: present
    name:
    - xdg-utils
  when: ansible_os_family == 'RedHat'

- name: Ensure xdg mime default application is set
  ansible.builtin.command: "xdg-mime default {{ item[0].desktop_file }} {{ item[1] }}"
  changed_when: False
  with_subelements:
    - "{{ xdg_mime_defaults }}"
    - mime_types
  vars:
    xdg_mime_defaults:
    - desktop_file: org.kde.kate.desktop
      mime_types:
      - text/plain
      - text/xml

- name: Kate preferences
  community.general.ini_file:
    path: ~/.config/katerc
    section: '{{ item.section }}'
    option: '{{ item.option }}'
    value: '{{ item.value }}'
    no_extra_spaces: yes
    mode: 0600
  loop:
    - section: KTextEditor Document
      option: ReplaceTabsDyn
      value: 'false'
    - section: KTextEditor Document
      option: Swap Directory
      value: /tmp/
    - section: KTextEditor Document
      option: Swap File Mode
      value: 2

- name: Create Konsole profile directory
  ansible.builtin.file:
    path: '~/.local/share/konsole'
    mode: 0775
    state: directory
  when: with_konsole_profiles

- name: Copy Konsole profiles
  ansible.builtin.copy:
    src: "konsole/"
    dest: "~/.local/share/konsole/"
    mode: 0600
  when: with_konsole_profiles

- name: Yakuake preferences
  community.general.ini_file:
    path: ~/.config/yakuakerc
    mode: 0600
    section: '{{ item.section }}'
    option: '{{ item.option }}'
    value: '{{ item.value }}'
    no_extra_spaces: yes
  loop:
    - section: Appearance # https://wiki.archlinux.org/title/Yakuake#Background_transparency_and_blur_on_Plasma
      option: Blur
      value: 'true'
    - section: Appearance
      option: Translucency
      value: 'true'
    - section: Desktop Entry
      option: DefaultProfile
      value: Apricot.profile
    - section: Window
      option: Height
      value: 70

- name: Install kwalletmanager and ksshaskpass
  become: true
  ansible.builtin.package:
    state: present
    name:
    - kwalletmanager
    - ksshaskpass

- name: Create autostart directory
  ansible.builtin.file:
    path: '~/.config/autostart'
    mode: 0755
    state: directory

- name: Copy ssh-add.desktop
  ansible.builtin.copy:
    src: "kde-ssh/ssh-add.desktop"
    dest: "~/.config/autostart/"
    mode: 0644

# inspired by AUR package plasma-workspace-agent-ssh

- name: Create /etc/xdg/plasma-workspace/env/
  become: true
  ansible.builtin.file:
    path: '/etc/xdg/plasma-workspace/env/'
    mode: 0755
    state: directory

- name: Create /etc/xdg/plasma-workspace/shutdown/
  become: true
  ansible.builtin.file:
    path: '/etc/xdg/plasma-workspace/shutdown/'
    mode: 0755
    state: directory

- name: Copy ssh-agent-startup.sh
  become: true
  ansible.builtin.copy:
    src: "kde-ssh/ssh-agent-startup.sh"
    dest: "/etc/xdg/plasma-workspace/env/"
    mode: 0755

- name: Copy askpass.sh
  become: true
  ansible.builtin.copy:
    src: "kde-ssh/askpass.sh"
    dest: "/etc/xdg/plasma-workspace/env/"
    mode: 0755

- name: Copy ssh-agent-shutdown.sh
  become: true
  ansible.builtin.copy:
    src: "kde-ssh/ssh-agent-shutdown.sh"
    dest: "/etc/xdg/plasma-workspace/shutdown/"
    mode: 0755
