---
# tasks file for my_kde_role
- name: System details
  ansible.builtin.debug:
    msg: "{{ item }}"
  with_items: 
  - "ansible_os_family: {{ ansible_os_family }}"
  - "ansible_distribution: {{ ansible_distribution }}"
  - "ansible_distribution_release: {{ ansible_distribution_release }}"
  - "ansible_distribution_version: {{ ansible_distribution_version }}"
  - "ansible_distribution_major_version: {{ ansible_distribution_major_version }}"
